version: '3'

volumes:
  prometheus_data: {}

services:

  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus:v2.37.6
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./nginx_alert_rules.yml:/etc/prometheus/nginx_alert_rules.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    links:
      - alertmanager:alertmanager
    ports:
      - 9090:9090
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 300M
        reservations:
          cpus: '0.2'
          memory: 200M

  prometheus_node_exporter:
    image: prom/node-exporter:v1.5.0
    container_name: node_exporter
    ports:
      - 9100:9100

  alertmanager:
    container_name: alertmanager
    hostname: alertmanager
    image: prom/alertmanager:v0.25.0
    volumes:
      - ./alertmanager.conf:/etc/alertmanager/alertmanager.conf
    command:
      - '--config.file=/etc/alertmanager/alertmanager.conf'
    ports:
      - 9093:9093

  nginx:
    image: nginx:1.23.3
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  nginx_node_exporter:
    image: nginx/nginx-prometheus-exporter:0.11
    container_name: nginx_exporter
    command:
    - '-nginx.scrape-uri=http://nginx:80/metrics'
    ports:
      - 9113:9113      